version: '2'

services:
  client:
    build: ./client
    image: calories/client
    container_name: cal_client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
    restart: always
  server:
    build: ./server
    image: calories/server
    container_name: cal_server
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=docker
    links:
      - db
    depends_on:
      - db
    restart: always
  db:
    image: "mongo"
    container_name: cal_db
    ports:
      - "27017:27017"
    restart: always
